# Generated by Django 6.0 on 2025-12-08 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impresoras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Asignado en'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='assignment_reason',
            field=models.TextField(blank=True, verbose_name='Razón de Asignación'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revisado en'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('URV', 'En Revisión'), ('APP', 'Aprobado'), ('REJ', 'Rechazado'), ('ASS', 'Asignado a Impresora'), ('PRI', 'Imprimiendo'), ('PAU', 'Pausado'), ('COM', 'Completado'), ('CAN', 'Cancelado'), ('FAI', 'Fallido')], default='PEN', max_length=3, verbose_name='Estado'),
        ),
    ]
